app:
  auth:
    accessTokenSecret: ${ACCESS_TOKEN_SECRET}
    refreshTokenSecret: ${REFRESH_TOKEN_SECRET}
    accessTokenExpiry: 86400000
    refreshTokenExpiry: 604800000

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB